# This file is generated by [bash-completor](https://github.com/adoyle-h/bash-completor/tree/v0.1.0). Do not modify it manually.
#
# [Usage]
# Put "source nvim-completion.bash" in your bashrc.
#
# If you want to debug the completion.
# Search '# Uncomment this line for debug' line in this file.
#
# [Update Script]
# bash-completor -c ./nvim.completor.bash
#
# [Version] 0.8.0
#
# [Maintainers]
# ADoyle (adoyle.h@gmail.com)

# shellcheck disable=2207
# editorconfig-checker-disable

_nvim_comp_cmd_opts=( - -t -q -- -e -E -es -Es -d -R -m -M -b -l -A -H -V -D -n -r -L -u -i --noplugin --clean -o -O -p + +/ -c --cmd -S -s -w -W --startuptime --api-info --embed --headless --listen -h --help -v --version )


_nvim_comp_reply_dirs ()
{
    local IFS=$'\n';
    compopt -o nospace -o filenames;
    COMPREPLY=($(compgen -A directory -- "$cur"))
}

_nvim_comp_reply_files ()
{
    local IFS=$'\n';
    compopt -o nospace -o filenames;
    COMPREPLY=($(compgen -A file -- "$cur"))
}

_nvim_comp_reply_files_in_pattern ()
{
    compopt -o nospace -o filenames;
    local path;
    while read -r path; do
        if [[ $path =~ $1 ]] || [[ -d $path ]]; then
            COMPREPLY+=("$path");
        fi;
    done < <(compgen -A file -- "$cur")
}

_nvim_comp_reply_list ()
{
    local IFS=', ';
    local array_list="" array_name;
    for array_name in $@;
    do
        array_list="$array_list \${${array_name}[*]}";
    done;
    array_list="${array_list[*]:1}";
    IFS=$'\n'' ';
    eval "COMPREPLY=( \$(compgen -W \"$array_list\" -- \"\$cur\") )"
}

_nvim_comp_reply_words ()
{
    local IFS=$'\n';
    COMPREPLY=($(IFS=', ' compgen -W "$*" -- "${cur#=}"))
}

_nvim_comp_reply_set() {
  local IFS=', '
  local array_list="" array_name
  # shellcheck disable=2068
  for array_name in $@; do
    array_list="$array_list \${_nvim_comp_var_${array_name}[*]}"
  done
  array_list="${array_list[*]:1}"

  IFS=$'\n'' '
  eval "COMPREPLY=( \$(compgen -W \"$array_list\" -- \"\$cur\") )"
}

_nvim_completions() {
  COMPREPLY=()
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=${COMP_WORDS[COMP_CWORD-1]}

  # Uncomment this line for debug
  # echo "[COMP_CWORD:$COMP_CWORD][cur:$cur][prev:$prev][WORD_COUNT:${#COMP_WORDS[*]}][COMP_WORDS:${COMP_WORDS[*]}]" >> bash-debug.log

  # Enter the cmd completion
  if [[ $COMP_LINE == *' -- '* ]]; then
    # When current command line contains the "--" option, other options are forbidden.
    _nvim_comp_reply_files
  elif [[ ${cur:0:1} == [-+] ]]; then
    # rely options of command
    _nvim_comp_reply_list _nvim_comp_cmd_opts
  elif [[ ${prev:0:1} == [-+] ]]; then
    case "${prev}" in
      # rely the value of command option
      -t)  ;;
      -c)  ;;
      --cmd)  ;;
      -s)  ;;
      *) _nvim_comp_reply_files ;;
    esac
  else
    # rely the argument of command
    _nvim_comp_reply_files
  fi
}

complete -F _nvim_completions -o bashdefault nvim
# vi: sw=2 ts=2
